FROM scratch
LABEL maintainer="mikucat <contact@mikuc.at>"
ARG TARGETARCH
ARG CACHE
ARG VERSION

COPY "${CACHE}/${VERSION}/${TARGETARCH}/xray" "${CACHE}/geoip.dat" "${CACHE}/dlc.dat" /

EXPOSE 443
CMD [ "/xray","-config","/config.json" ]

