name: build-multiarch-images

on: push

env:
  NAME: ${{ github.repository_owner }}/xray
  VERSION: 1.5.2
  PLATFORMS: |
    linux/386
    linux/amd64
    linux/arm/v6
    linux/arm/v7
    linux/arm64
    linux/mips64
    linux/mips64le
    linux/ppc64le
    linux/riscv64
    linux/s390x

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Containerfile.architecture
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ghcr.io/${{ env.NAME }}:latest
            ghcr.io/${{ env.NAME }}:${{ env.VERSION }}
          build-args: VERSION=${{ env.VERSION }}

